"""add new column in PostLike Table

Revision ID: de34a79e165b
Revises: 80263d4031f5
Create Date: 2023-07-02 19:20:31.395289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de34a79e165b'
down_revision = '80263d4031f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'like', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.drop_column('like', 'owner_id')
    # ### end Alembic commands ###
