"""add new column in PostLike Table2

Revision ID: f90d5eb4b01b
Revises: de34a79e165b
Create Date: 2023-07-02 19:25:05.213388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f90d5eb4b01b'
down_revision = 'de34a79e165b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
